### ISSUE TITLE
modernize logging

### ISSUE THREAD

**Issue by glyph** [twisted/ampoule#22]
Ampoule presently makes heavy use of (old, one-day-hopefully deprecated) `log.msg`, and worse yet, frequently does string interpolation on log messages (see [here](https://github.com/twisted/ampoule/blob/6f4fc2e9775132beb797dfd822266e3c96357369/ampoule/main.py#L97) for example).

Let's clean this up to use `twisted.logger`.

**Comment by ldanielburr** [comment]
Only a few files involved, I'll take a crack at this.  I think .msg should generally be treated as .info in twisted.logger parlance.  For logging occurring in error-handling code, I think .error is ok, although an operator might wish to have the option to change .error to .failure if they want to see tracebacks.

**Comment by ldanielburr** [comment]
I put together PR #29 for this.  It is a pretty short read when/if someone has a moment.

**Comment by ldanielburr** [comment]
I should also note that the labels available here in the ampoule repository differ from the twisted repository.  Most notably, there is no "review required" label here in ampoule.

**Comment by glyph** [comment]
Fixed in #29 .
